name: testapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  google_fonts: ^6.2.1
  google_sign_in:
  sign_in_button:
  intl_phone_field: ^3.2.0
  geolocator: ^10.1.0
  shared_preferences: ^2.3.2
  flutter_rounded_date_picker:
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.3

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  http:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: NoirPro
      fonts:
        - asset: fonts/NoirPro/NoirPro-Regular.otf
        - asset: fonts/NoirPro/NoirPro-Medium.otf
          weight: 500
        - asset: fonts/NoirPro/NoirPro-Light.otf
          weight: 300
        - asset: fonts/NoirPro/NoirPro-Bold.otf
          weight: 700
        - asset: fonts/NoirPro/NoirPro-Italic.otf
          style: italic


fonts:
  - family: Baskerville
    fonts:
      - asset: fonts/Baskerville.ttf

